 all: main.cpp Track.cpp Session.cpp Conference.cpp SessionOrganizer.cpp
	  g++ -o main main.cpp Track.cpp Session.cpp Conference.cpp SessionOrganizer.cpp

debug: main.cpp Track.cpp Session.cpp Conference.cpp SessionOrganizer.cpp
	  g++ -g -o main main.cpp Track.cpp Session.cpp Conference.cpp SessionOrganizer.cpp
